<a href="https://colab.research.google.com/github/durgeshgitup/MA22C013_2023_PL/blob/main/Assignment/Assignment_5/Row_swap.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def swaprow(i, j, A):
  tmp = A[i, :]
  A[i, :] = A[j, :]
  A[j, :] = tmp
  return A

In [ ]:
def swaprow_1(i, j, A):
  A[[i,j]] = A[[j,i]]
  return A

In [ ]:
A = np.array([[5,7,6],[2,6,7],[8,9,1]])
print(A)

[[5 7 6]
 [2 6 7]
 [8 9 1]]


In [ ]:
swaprow_1(0,1,A)

array([[2, 6, 7],
       [5, 7, 6],
       [8, 9, 1]])