<a href="https://colab.research.google.com/github/durgeshgitup/MA22C013_2023_PL/blob/main/Assignments/Assignment_6/Pairwise_differences.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

x = np.random.rand(5)
D = np.subtract.outer(x, x)

print(D)


[[ 0.         -0.95681577 -0.81772352 -0.49678061 -0.30733871]
 [ 0.95681577  0.          0.13909225  0.46003516  0.64947706]
 [ 0.81772352 -0.13909225  0.          0.32094291  0.5103848 ]
 [ 0.49678061 -0.46003516 -0.32094291  0.          0.18944189]
 [ 0.30733871 -0.64947706 -0.5103848  -0.18944189  0.        ]]
