<a href="https://colab.research.google.com/github/durgeshgitup/MA22C013_2023_PL/blob/main/Assignments/Assignment_8/Column_Space.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Task 1: Computing Basis for the Column Space Using QR and SVD

In [13]:
import numpy as np
from scipy.linalg import qr
from scipy.linalg import svd
A = np.array([[1, -2, 3], [2, -4, 9], [-3, 6, -9]])
Q, R = qr(A, mode='economic')
column_space_basis_qr = Q

In [14]:
A

array([[ 1, -2,  3],
       [ 2, -4,  9],
       [-3,  6, -9]])

In [15]:
U, S, Vt = np.linalg.svd(A)
column_space_basis_svd = U
print(column_space_basis_svd)

[[-2.41287499e-01  2.04402404e-01  9.48683298e-01]
 [-6.46377156e-01 -7.63018068e-01  2.77555756e-16]
 [ 7.23862498e-01 -6.13207212e-01  3.16227766e-01]]


In [16]:
# We compute a basis for the column space using QR factorization
Q, _ = qr(A, mode='economic')
column_space_basis_qr = Q

# We Compute a basis for the column space using SVD
U, _, _ = svd(A)
column_space_basis_svd = U
print("Basis for the column space using QR:")
print(column_space_basis_qr)
print("\nBasis for the column space using SVD:")
print(column_space_basis_svd)

Basis for the column space using QR:
[[-0.26726124  0.95618289 -0.11952286]
 [-0.53452248 -0.04390192  0.84401323]
 [ 0.80178373  0.28945968  0.52283453]]

Basis for the column space using SVD:
[[-2.41287499e-01  2.04402404e-01  9.48683298e-01]
 [-6.46377156e-01 -7.63018068e-01  2.77555756e-16]
 [ 7.23862498e-01 -6.13207212e-01  3.16227766e-01]]


# Task 2: Checking Equivalence of Column Spaces

In [17]:
# Basis of column space using QR factorization
Q, _ = qr(A, mode='economic')

# Basis of column space using SVD
U, _, _ = svd(A)

# if the dimensions of the column spaces are the same
if Q.shape[1] == U.shape[1]:
    print("Dimensions of column spaces are the same.")

# if the column spaces have the same subspace spanned by the basis vectors
if np.allclose(np.dot(A, Q), np.dot(A, U)):
    print("Column spaces are the same.")
else:
    print("Column spaces are different.")

Dimensions of column spaces are the same.
Column spaces are different.


# Task 3: Comparing the Speed of QR and SVD for a 500x500 Random Matrix

In [19]:
import timeit
# Compute a random 500x500 matrix
np.random.seed(0)  # for reproducibility
A = np.random.rand(500, 500)

# Timing for QR factorization
qr_time = timeit.timeit(lambda: qr(A, mode='economic'), number=100)

# Timing for SVD
svd_time = timeit.timeit(lambda: svd(A), number=100)

print(f"Time taken for QR factorization: {qr_time:.4f} seconds")
print(f"Time taken for SVD: {svd_time:4f} seconds")

if qr_time < svd_time:
    print("QR factorization is faster.")
else:
    print("SVD is faster.")

Time taken for QR factorization: 3.0883 seconds
Time taken for SVD: 14.265739 seconds
QR factorization is faster.
